# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='BookingD',
            field=models.DateField(default='2017-01-01'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='BookingT',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
