# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Booking',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
