# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pservices', '0002_appointments_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Booking',
            field=models.DateTimeField(),
        ),
    ]
