# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pservices', '0003_auto_20170524_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductTitle', models.CharField(db_index=True, max_length=200)),
                ('ProductDescription', models.TextField(db_index=True, max_length=500)),
            ],
        ),
    ]
