# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pservices', '0003_auto_20170717_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductDescription',
            field=models.TextField(db_index=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='service',
            name='ServiceDescription',
            field=models.TextField(db_index=True, max_length=2500),
        ),
    ]
