# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pservices', '0005_appointments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Age',
            field=models.IntegerField(blank=True),
        ),
    ]
